export const CHARACTERS_UPDATE = 'CHARACTERS_UPDATE';
export const CHARACTERS_FAV_UPDATE = 'CHARACTERS_FAV_UPDATE';
export const CHARACTER_DETAIL_FAV_UPDATE = 'CHARACTER_DETAIL_FAV_UPDATE';
export const CHARACTER_DETAIL_UPDATE = 'CHARACTER_DETAIL_UPDATE';